---
- name: show blocks and when
  hosts: all
  become: yes

  tasks:
    # For Centos, feroda, etc
    - block: 

      - name: Removing nginx
        yum:
          name: nginx
          state: absent

      - name: Install packages
        yum:
          name: httpd
          state: present


      - name: Enable service
        service:
          name: httpd
          state: started

      when: ansible_os_family == "RedHat"
    
    # For Ubuntu, debian, linux mint, etc
    - block:
      - name: Removing nginx
        apt:
          name: nginx
          state: absent

      - name: Install packages
        apt:
          name: apache2
          state: present


      - name: Enable service
        service:
          name: apache2
          state: started
      when: ansible_os_family == "Debian"